---
title: "Twin Count Data EDA"
author: "Carter Allen"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
knitr::opts_knit$set(root.dir = "/Users/carterallen/Documents/School/Research")
```

```{r, message=FALSE, warning=FALSE}
# packages
library(edgeR)
library(tidyverse)
library(pheatmap)
```

## Form DGEList

```{r}
# Read count data
counts <- read.table("Data/Disease_vs_Control_Counts.txt", 
                     header = TRUE, 
                     sep = '\t')
counts_mat <- counts[,-1] # remove row name row
genes <- as.character(counts[,1]) # pull genes

# Read group data
groups_df <- read.table("Data/Disease_vs_Control_groups.txt",
                       header = TRUE,
                       sep = '\t') %>%
    mutate(patient = factor(patient,
                            levels = c("one",
                                       "two",
                                       "three",
                                       "four",
                                       "five",
                                       "six",
                                       "seven",
                                       "eight",
                                       "nine",
                                       "ten",
                                       "eleven",
                                       "twelve",
                                       "thirteen",
                                       "fourteen",
                                       "fifteen",
                                       "sixteen")),
           twin_pair = as.numeric(patient))


# get groups
groups <- groups_df %>%
    pull(condition) %>%
    as.character()

# Get sample order
samples <- groups_df %>%
    pull(samples) %>%
    as.character()

# arrange columns
counts_mat <- counts_mat[,samples]

# add case/control labels to column names
colnames(counts_mat) <- paste(colnames(counts_mat),
                              groups,
                              sep = "_")

# Form DGEList
y <- DGEList(counts = counts_mat,
             genes = genes,
             group = groups)

# Order and remove duplicates
o <- order(rowSums(y$counts), decreasing=TRUE)
y <- y[o,]
d <- duplicated(y$genes$genes)
y <- y[!d,]

# Normalization
y <- calcNormFactors(y)
```

## Unfiltered correlation among samples heatmap

```{r}
cor_plot <- pheatmap(cor(cpm(y)),
                     cluster_rows = F,
                     cluster_cols = F)
cor_plot

```

## Unfiltered MDS plot

```{r}
plotMDS(y)
```

## Filtered correlation among samples heatmap

```{r}
n.pre <- nrow(y)
n.pre
y <- y[rowSums(cpm(y) > 1) >= 3,,keep.lib.sizes = FALSE]
n.post <- nrow(y)
n.post
cor_plot_filtered <- pheatmap(cor(cpm(y)),
                              cluster_rows = F,
                              cluster_cols = F)
```

## Filtered MDS plot

```{r}
plotMDS(y)
```

## Heatmap of CPMs

```{r}
count_plot <- pheatmap(log10(cpm(y) + 1),
                       cluster_cols = F,
                       cluster_rows = F,
                       show_rownames = F)
```

